[build]
builder = "nixpacks"
buildCommand = "cd artifacts/api-server && npm install --include=dev && node ./build.mjs"

[deploy]
startCommand = "node --enable-source-maps artifacts/api-server/dist/index.mjs"
healthcheckPath = "/api/healthz"
healthcheckTimeout = 30
restartPolicyType = "always"
