name: 🚀 Deploy Bot a Railway

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy a Railway
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy a Railway
        run: railway up --service ca622ead-b524-4296-9a6a-59a33b6b38a5 --environment 70546448-a18d-471a-aec0-05206d08d502 --detach
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
